services:
  mysql-server-db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PRO_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql

  gamech-server-app:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      CLIENT_PORT: ${CLIENT_PORT}
      WIFI_URL: ${WIFI_URL}
      MYSQL_DEV_USERNAME: ${MYSQL_DEV_USERNAME}
      MYSQL_DEV_PASSWORD: ${MYSQL_DEV_PASSWORD}
      MYSQL_DEV_HOST: ${MYSQL_DEV_HOST}
      MYSQL_DEV_PORT: ${MYSQL_DEV_PORT}
      MYSQL_PRO_USERNAME: ${MYSQL_PRO_USERNAME}
      MYSQL_PRO_PASSWORD: ${MYSQL_PRO_PASSWORD}
      MYSQL_PRO_HOST: ${MYSQL_PRO_HOST}
      MYSQL_PRO_PORT: ${MYSQL_PRO_PORT}
      MYSQL_DB: ${MYSQL_DB}
      SERVER_URL: ${SERVER_URL}
      CLIENT_URL: ${CLIENT_URL}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      AT_SECRET: ${AT_SECRET}
      RT_SECRET: ${RT_SECRET}
      AL_SECRET: ${AL_SECRET}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      - mysql-server-db

volumes:
  mysql_data:
